# http://gitpod.io/#github.com/gnolang/gnochess

additionalRepositories:
  - url: https://github.com/gnolang/gno
    checkoutLocation: gno

# gnoland and gnoweb need to reference local files.
# gnokey and gno don't, and they are versioned using their values
# in go.mod
tasks:
  - name: Gnoland
    before: cd ../gno/gno.land/
    init: |
      git fetch --all
      git switch patch/gnochess
      touch /workspace/.init.switch
      go install ./cmd/gnoland ./cmd/gnoweb
      touch /workspace/.init.install
    command: gnoland start

  - name: Gnoweb
    init: while [ ! -f /workspace/.init.install ]; do sleep 1; done
    before: cd ../gno/gno.land/;
    command: gnoweb --bind=0.0.0.0:8888

  - name: Deps
    before: cd ../gno/misc/devdeps
    init: |
      while [ ! -f /workspace/.init.switch ]; do sleep 1; done
      make install
      echo "Deps installed."

  - name: Gno CLI
    init: |
        go mod download
        go install \
          github.com/gnolang/gno/gno.land/cmd/gnokey \
          github.com/gnolang/gno/gnovm/cmd/gno
    command: gno --help

ports:
  - name: gnoweb
    description: "the Gno.land web server"
    port: 8888
    onOpen: open-preview

  - name: "gnoland RPC"
    description: "the RPC server, managed by tendermint2"
    port: 36657
    onOpen: notify

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: true

workspaceLocation: '/workspace/gnochess/tutorial'

vscode:
  extensions:
    - harry-hov.gno
